baseURL = 'https://mahiequalslollies.com/cooroora/'
locale = 'en'
defaultcontentlanguage = "en"
title = 'Cooroora Blog'
theme = ["hugo-embed-pdf-shortcode", "blowfish"]
enableInlineShortcodes = true


